name: Windows Build

on:
  push:
    branches:
      - main  # Adjust this if your main branch has a different name
  pull_request:
    branches:
      - main  # Adjust this if your main branch has a different name

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'  # Adjust according to your specific Python version requirement

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install numpy pygame dxfwrite pandas openpyxl opencv-python matplotlib pcbnew  # Ensure pcbnew is available via pip or adjust accordingly

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile PCBcoilV2.py  # Ensure this points to your main Python script

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: dist/*.exe
