name: Build Windows Executable

on:
  push:
    branches:
      - feature/add-loop-antenna-option
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller numpy pygame dxfwrite pandas openpyxl opencv-python matplotlib

    - name: Build Executable
      run: pyinstaller --onefile PCBcoilV2.py  # Update this with your actual script name

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-executable
        path: dist/*.exe

